import json

json_data = [
  "denali",
  "gatesOfTheArctic",
  "glacierBay",
  "katmai",
  "kenaiFjords",
  "kobukValley",
  "lakeClark",
  "wrangellStElias",
  "americanSamoa",
  "grandCanyon",
  "petrifiedForest",
  "saguaro",
  "hotSprings",
  "channelIslands",
  "deathValley",
  "joshuaTree",
  "kingsCanyon",
  "lassenVolcanic",
  "redwood",
  "pinnacles",
  "sequoia",
  "yosemite",
  "blackCanyonOfTheGunnison",
  "greatSandDunes",
  "mesaVerde",
  "rockyMountain",
  "biscayne",
  "dryTortugas",
  "everglades",
  "haleakala",
  "hawaiiVolcanoes",
  "yellowstone",
  "indianaDunes",
  "mammothCave",
  "acadia",
  "isleRoyale",
  "voyageurs",
  "gatewayArch",
  "glacier",
  "greatBasin",
  "carlsbadCaverns",
  "whiteSands",
  "greatSmokyMountains",
  "theodoreRoosevelt",
  "cuyahogaValley",
  "craterLake",
  "congaree",
  "badlands",
  "windCave",
  "bigBend",
  "guadalupeMountains",
  "virginIslands",
  "arches",
  "bryceCanyon",
  "canyonlands",
  "capitolReef",
  "zion",
  "shenandoah",
  "mountRainier",
  "northCascades",
  "olympic",
  "newRiverGorge",
  "grandTeton"
]


def sort_by_last_two_chars(strings):
  return sorted(strings, key=lambda x: x[-2:])

with open('modified_data.json', 'w') as json_file:
    json.dump(sorted(json_data), json_file, indent=2)