import json

# Given list data
countyIDs = [
  "Santa_Clara__CA",
  "Alameda__CA",
  "San_Joaquin__CA",
  "Stanislaus__CA",
  "Tuolumne__CA",
  "Mariposa__CA",
  "Mono__CA",
  "Mineral__NV",
  "Esmeralda__NV",
  "Nye__NV",
	"Lincoln__NV",
	"Iron__UT",
	"Beaver__UT",
  "Millard__UT",
  "Sevier__UT",
  "Emery__UT",
  "Grand__UT",
	"Mesa__CO",
	"Garfield__CO",
	"Eagle__CO",
	"Summit__CO",
	"Clear_Creek__CO",
	"Jefferson__CO",
	"Denver__CO",
	"Adams__CO",
	"Arapahoe__CO",
	"Douglas__CO",
	"El_Paso__CO",
	"Fremont__CO",
	"Custer__CO",
	"Pueblo__CO",
	"Huerfano__CO",
	"Costilla__CO",
	"Alamosa__CO",
	"Conejos__CO",
  "Rio_Arriba__NM",
  "Taos__NM",
  "Santa_Fe__NM",
	"Los_Alamos__NM",
  "Sandoval__NM",
  "Bernalillo__NM",
	"San_Juan__NM",
	"La_Plata__CO",
	"San_Juan__CO",
	"Ouray__CO",
	"Montrose__CO",
	"Delta__CO",
	"Gunnison__CO",
	"Pitkin__CO",
	"Lake__CO",
	"Weld__CO",
	"Morgan__CO",
	"Washington__CO",
	"Logan__CO",
	"Sedgwick__CO",
	"Deuel__NE",
	"Keith__NE",
	"Lincoln__NE",
	"Dawson__NE",
	"Buffalo__NE",
	"Hall__NE",
	"Hamilton__NE",
	"York__NE",
	"Seward__NE",
	"Lancaster__NE",
	"Cass__NE",
	"Sarpy__NE",
	"Douglas__NE",
	"Pottawattamie__IA",
	"Cass__IA",
	"Adair__IA",
	"Madison__IA",
	"Dallas__IA",
	"Polk__IA",
	"Jasper__IA",
	"Marion__IA",
	"Mahaska__IA",
	"Poweshiek__IA",
	"Tama__IA",
	"Marshall__IA",
	"Story__IA",
	"Hamilton__IA",
	"Franklin__IA",
	"Wright__IA",
	"Cerro_Gordo__IA",
	"Worth__IA",
	"Freeborn__MN",
	"Steele__MN",
	"Rice__MN",
	"Scott__MN",
	"Dakota__MN",
  "Hennepin__MN",
  "Ramsey__MN",
  "Washington__MN",
	"St__Croix__WI",
	"Polk__WI",
  "Chisago__MN",
  "Anoka__MN",
	"Le_Sueur__MN",
	"Sibley__MN",
	"Nicollet__MN",
	"Blue_Earth__MN",
	"Watonwan__MN",
	"Cottonwood__MN",
	"Jackson__MN",
	"Nobles__MN",
	"Osceola__IA",
	"Lyon__IA",
	"Lincoln__SD",
	"Minnehaha__SD",
	"McCook__SD",
	"Hanson__SD",
	"Davison__SD",
	"Aurora__SD",
	"Brule__SD",
	"Lyman__SD",
	"Jones__SD",
	"Jackson__SD",
	"Pennington__SD",
	"Meade__SD",
	"Lawrence__SD",
	"Butte__SD",
	"Crook__WY",
	"Weston__WY",
	"Custer__SD",
	"Fall_River__SD",
	"Niobrara__WY",
	"Converse__WY",
	"Natrona__WY",
	"Carbon__WY",
	"Fremont__WY",
	"Sublette__WY",
	"Sweetwater__WY",
	"Lincoln__WY",
	"Uinta__WY",
	"Summit__UT",
  "Salt_Lake__UT",
  "Utah__UT",
  "Wasatch__UT",
	"Tooele__UT",
	"Elko__NV",
  "Eureka__NV",
  "Lander__NV",
  "Humboldt__NV",
  "Pershing__NV",
  "Churchill__NV",
  "Lyon__NV",
  "Storey__NV",
  "Washoe__NV",
  "Sierra__CA",
  "Nevada__CA",
  "Placer__CA",
  "Sacramento__CA",
  "Yolo__CA",
  "Solano__CA",
  "Contra_Costa__CA",
  "San_Francisco__CA",
  "San_Mateo__CA"
]


visits = []
for county_id in countyIDs:
    visit = {
        "id": county_id,
        "visitDate": "2004-07-30",
        "countyName": county_id
    }
    visits.append(visit)

# Write the modified data back to the JSON file
with open('visits.json', 'w') as json_file:
    json.dump(visits, json_file, indent=2)

print("Visits data saved to 'visits.json'")
